version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: email
        tests:
          - not_null
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: amount
        tests:
          - accepted_values:
              values: [100.50, 150.00, 200.75]
  - name: stg_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: category
        tests:
          - accepted_values:
              values: ['Electronics', 'Clothing']